# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-font", "~> 0.5.0"

gem "tty-progressbar", "~> 0.11.0"

gem "pastel"

gem "rspec", "~> 3.9"

gem 'tty-prompt'

gem 'tty-cursor', "~> 0.3.0"

gem 'terminal-table'
